### ISSUE TITLE
добавить имя автора после новости, пост нескольких новостей

### ISSUE THREAD

**Issue by 4vanyek** [selezneww/probable-waddle#3]
ну например: "новость - автор, дата" (без кавычек только)
и так как я в js не разбираюсь, то прошу тебя сделать это

**Comment by 4vanyek** [comment]
ответ получен, issue закрываю:
> По поводу твоих коммитов. 1. будет только одна новость, ибо в localstorage можно записать только один текст, массив нельзя. 2. возможно можно будет только сделать Автор/новость, ибо я хз как снять дату/время через js)

**Comment by selezneww** [comment]
Возможность добавления нескольких новостей вероятней всего будет. Имя автора перед новостью. Актуально

**Comment by 4vanyek** [comment]
@selezneww а можно как-то сделать, чтобы имя автора и новость были рядом друг с другом, а не через строчку? Типа так: "автор: новость", а не "автор
новость"

**Comment by selezneww** [comment]
> @selezneww а можно как-то сделать, чтобы имя автора и новость были рядом друг с другом, а не через строчку? Типа так: "автор: новость", а не "автор новость"

не знаю точно, но видимо нельзя, я пытался

**Comment by 4vanyek** [comment]
> не знаю точно, но видимо нельзя, я пытался

можно конечно один p тег засунуть в другой (типа так: `<p id="news-author><p id="news-text"></p></p>`) но это уже костыль будет (или как нибудь с div'ом)

**Comment by selezneww** [comment]
Неактуально.
